### ISSUE TITLE
Distinguishable window titles

### ISSUE THREAD

**Issue by VuiMuich** [Alteka/Kards#100]
Currently both the config window and the (windowed) testpattern output us the same window title `Kards`.

It would be nice if they would have distinguishable difference like `Kards - Config` and `Kards - Output`, so screen capture apps like OBS would not be confused, which window to capture.

**Comment by DrewLX** [comment]
This is an easy win, I have updated and pushed to master. Will be included in the next release which I'm hoping to do in the next few weeks to celebrate having 10,000 downloads.
