### ISSUE TITLE
Kards does not close or disables

### ISSUE THREAD

**Issue by FranklinL** [Alteka/Kards#103]
On a MacBook pro, with Kards 1.3.0, when enabled with the test card on external display, toggling the enable button or using the command+f shortcut does not close the test card. Also, a save card popup appears when trying to toggle the enable to stop the test card. Only force quit closes the test card.

Same symptoms on 3 different MacBook Pro.

All running MacOS 13.5, with M1 Pro MBP.

**Comment by DrewLX** [comment]
Fixed in version 1.3.1
