### ISSUE TITLE
Mac OSD detecting your software as malware

### ISSUE THREAD

**Issue by sweetapollo** [Alteka/Kards#107]
Hi. I have used Kards for quite along time now, but today my Mac stated this software was malware and removed it for me. I redownloaded it as a newer version and also just in case my version was corrupt, but once again nit is stating it is malware and removing it for me. I am not sure if there is a problem with your server being hacked or if it is a false positive, but I thought you should know.

**Comment by BanDamber** [comment]
Sadly I can also confirm this. I have an M1 Macbook Pro (Silicon) which has stopped the latest version of Kards being available as it flags it as malware. I have also uninstalled my (previously) working version and downloaded the latest, which hasn't solved the issue. Pic attached for reference. 
![KardMalwareIssueApril24](https://github.com/Alteka/Kards/assets/165835451/352b80e8-ce7e-4a78-a4a4-086e395442fb)

**Comment by BanDamber** [comment]
Version 1.2 does appear to work.. I shall try running that for the foreseeable and await an update.

**Comment by rileyhutton** [comment]
Having the same issue, both on the universal and apple silicon builds. M1 Pro, MacOS 14.4

**Comment by canoemoose** [comment]
Thanks everyone, this has been fixed and 1.3.1 released just now.
Please open a new issue if you're still having problems!
