### ISSUE TITLE
Cancelling file save dialog for image export throws an error

### ISSUE THREAD

**Issue by canoemoose** [Alteka/Kards#11]
![Error](https://user-images.githubusercontent.com/16150841/82435351-15cbd400-9a8c-11ea-92c2-b5576f7a4470.jpeg)

**Comment by DrewLX** [comment]
Just need to wrap the fs.writeFile around an if statement to check that a destination was selected.Around line 135 of index.js

**Comment by canoemoose** [comment]
I was starting work on this when I discovered my unable-to-export woes - I have some stashed changes that I think fixes it, but I'm currently unable to test.
