### ISSUE TITLE
Enabling the output does not show on the selected screen on a Mac

### ISSUE THREAD

**Issue by garethnunns** [Alteka/Kards#19]
When enabling the test card output for an external display it is shown on the primary display.

### Environment

- Kards 0.6.0
- macOS Mojave - 10.14.6
- MacBook Pro (Retina, 15-inch, Mid 2015)
- One external display (ViewSonic VP2780) attached via HDMI
- Display configured second screen (not mirrored)
- Scaled to 2560x1440
- _Display have separate Spaces_ enabled

_(Have also tested with two external screens)_

### To reproduce

1. Select the resolution of the external display
2. Press enable

![kards](https://user-images.githubusercontent.com/2584408/83411258-c7192500-a40f-11ea-8496-ec9b63b2becd.gif)

### Expected behaviour

For the output to show on the selected screen

### Actual behaviour

The output shows on the primary monitor _(regardless of which display the control window is shown on)_

**Comment by DrewLX** [comment]
Interesting behaviour! I haven't tested on anything other than Catalina...

**Comment by garethnunns** [comment]
I'm still on Mojave for a few 64 bit apps, but most show machines would be on Catalina

**Comment by DrewLX** [comment]
If you have 'Displays have separate spaces' turned off, does it do the same thing or does it then function correctly?

**Comment by canoemoose** [comment]
I'm still on 10.14.6 myself - I can confirm Gareth's reported behaviour.
With 'Displays have separate Spaces' off, it functions correctly for me.

**Comment by garethnunns** [comment]
Yes I had the same experience as @canoemoose, with _Displays have separate Spaces_ disabled it works as expected. Same behaviour on 10.13.6

**Comment by DrewLX** [comment]
This is fixed. Thanks @garethnunns for helping me test.
