### ISSUE TITLE
Test Card to wallpaper produces square image with test card at the top.  Canvas to wallpaper works as expected.

### ISSUE THREAD

**Issue by canoemoose** [Alteka/Kards#3]

**Comment by DrewLX** [comment]
I'd say this is only true on windows... I can't replicate.

**Comment by canoemoose** [comment]
Interesting. This is the file it sets as wallpaper for me:
![TranscodedWallpaper3](https://user-images.githubusercontent.com/16150841/81927453-90ec4080-95db-11ea-9e41-20b3843b4794.png)

**Comment by DrewLX** [comment]
Test card to file doesn't make it like that?

**Comment by canoemoose** [comment]
Fixed in 350e1163c49386c4752c8b4b5042f6cbdb918b9a
