### ISSUE TITLE
Windows: Windowed card grows when moved between monitors of different DPI scaling factors

### ISSUE THREAD

**Issue by canoemoose** [Alteka/Kards#30]

**Comment by canoemoose** [comment]
Still happens as of 6c3a952
Also, dragging card from one screen to another of a different DPI scaling factor is a lot buggier than before.

**Comment by DrewLX** [comment]
Even in a built app?

**Comment by DrewLX** [comment]
That commit works, and doesn't seem to have any negative repercussions but it's a slightly crude solution!
