### ISSUE TITLE
Long names linewrap awkwardly in the infocircle

### ISSUE THREAD

**Issue by canoemoose** [Alteka/Kards#39]
Maybe they should shrink instead.
From Reddit - [link](https://www.reddit.com/r/VIDEOENGINEERING/comments/kt7d81/introducing_alteka_kards_a_new_test_card_app/gil3yvv/)

![TUfcQL7](https://user-images.githubusercontent.com/16150841/104067115-7b76f700-51fa-11eb-9679-7f2894a7f95a.png)

**Comment by DrewLX** [comment]
That's challenging but possible. Would have to resort to just counting characters and dropping the size at various lengths.

**Comment by tcconway** [comment]
Clunky workaround is to add a ton of spaces at the end of the text.

**Comment by DrewLX** [comment]
I've slightly improved this situation with additional steps in the calculation. It still not great with continous words but it works fine with the odd space here and there!
