### ISSUE TITLE
Additional free-text field text-to-speech voice output

### ISSUE THREAD

**Issue by canoemoose** [Alteka/Kards#42]
So you can leave a pattern up with a spoken "you should be seeing a pattern and hearing a voice"

**Comment by DrewLX** [comment]
So turn the existing "voice" option to name. And then add another one with an audio config parameter of text?

Or would the text be displayed on the output as well?

**Comment by canoemoose** [comment]
Yeah, first option.

Allows to have some spoken text, separate from the name, that isn't shared with output on the displayed card.

**Comment by DrewLX** [comment]
This is pretty simple to do, I'm not sure I see a real use case but it's clean enough UI so I'll look at implementing this for 1.2 release.

**Comment by DrewLX** [comment]
Implemented, quite happy with it but the drawer height isn't perfect. @canoemoose Have a look at the branch dev-1.2.0 and see what you think.

**Comment by DrewLX** [comment]
I've improved the UI layout and tested this further. Closing as enhancement is on branch and will be in the next release.
