### ISSUE TITLE
Installer with choice of install location and/or a portable version

### ISSUE THREAD

**Issue by canoemoose** [Alteka/Kards#43]
Someone was a little sad they got 300MB of stuff on their drive for "just" a test card app. The wonders of Electron...
Also pointed out a portable version might be good for the USB-stick-of-tools crowd - although personally I'd rather they had an installer and left a copy installed for other people to find...

**Comment by DrewLX** [comment]
I agree with the sentiment, but the solution is wrong. Let's first look into shrinking the 300meg down. The first step would be to move things from dependancies to devDependancies within package.json.

**Comment by DrewLX** [comment]
224 meg once installed and it now asks for location to install.
