### ISSUE TITLE
Text alignment is different between generated card and saved PNG

### ISSUE THREAD

**Issue by canoemoose** [Alteka/Kards#7]
Ever so slightly, can only be seen if compare screenshot and export and flick between them. Not sure there's anything to fix...

![Export](https://user-images.githubusercontent.com/16150841/82434544-e5376a80-9a8a-11ea-8616-d93bf1a0ec8c.jpeg)
![Screenshot](https://user-images.githubusercontent.com/16150841/82434561-ebc5e200-9a8a-11ea-9933-5d1598650e9b.jpeg)

**Comment by DrewLX** [comment]
This is probably down to the screen output being done at retina/HiDPI resolutions, whereas the picture export is at 'actual' pixels which causes a minor difference. Not really worth fixing but worth remembering.
