### ISSUE TITLE
Default grid size should be 32 pixels?

### ISSUE THREAD

**Issue by canoemoose** [Alteka/Kards#8]
Standard widescreen resolution widths are a multiple of 32. Sadly, unlike 4:3 resolutions, the heights aren't.
Could also use 64 for larger grid.
Step size of spinner buttons for grid cells would aslo need thinking about.

**Comment by DrewLX** [comment]
I think I disagree. Whilst 32 does multiply into the widths well, it means you can't quickly tell where you are by counting squares. You can type a number in quickly and it persists so it's a fairly minor point.

**Comment by DrewLX** [comment]
After discussion, keeping it at 50 but will review if more people suggest something different
