### ISSUE TITLE
Bonjour names can clash. Should be unique.

### ISSUE THREAD

**Issue by DrewLX** [Alteka/Kards#86]
The service name for Bonjour is always just "Kards" and so clashes if running twice on a network. Should include the host name of the computer

**Comment by canoemoose** [comment]
Running twice on the same machine would also clash, and gives the attached log error. 
host-Kards-<name>
[main.log](https://github.com/Alteka/Kards/files/8403014/main.log)
?

**Comment by DrewLX** [comment]
Yeah, I need to read the documentation and see if the library can generate the name etc.
