### ISSUE TITLE
Headshot Test Card

### ISSUE THREAD

**Issue by tcconway** [Alteka/Kards#93]
Would love an additional Kards slide - one that is a full-frame silhouette of a human, for a headshot/multibox framing.

I envision it would be a button to toggle on/off. Toggling on, it would show a full frame outline/silhouette of a human in a single headshot configuration over the existing layout.

Would be super useful when you're setting up multi-box shots!

**Comment by DrewLX** [comment]
I think there is a way of doing this and taking it a step further. Imagine an 'Overlay' toggle which allows you to then add your own image (SVG or PNG) to overlay infront of the kard. This should be scaled to fill but warn you if the aspect ratio doesn't match. 

That way if you were doing a projection and wanted to mask out a shape you could use the same feature. But if you wanted a single person you can do that.

**Comment by tcconway** [comment]
+1 to what @DrewLX posted. Love this idea better!!

**Comment by DrewLX** [comment]
This has pretty much been done on the master branch. It currently doesn't warn your if mis-matched aspect ratio but I have mixed feelings about how to do this element.

**Comment by DrewLX** [comment]
Improved this a little, and pushed to master. Will be in the next release - which should be soon!
